[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3
    mikalhart/TinyGPSPlus

monitor_port = COM9
monitor_speed = 115200

upload_port = COM9
upload_speed = 115200